<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */
?>

<style type="text/css">
    form#filter_form label {display: none;}
    .pagination {margin-top: 0px;}
    .custsubnav > li {text-align: left;}
    .btn-group > ul.dropdown-menu:before {
        border-bottom: 7px solid rgba(0, 0, 0, 0.2);
        border-left: 7px solid rgba(0, 0, 0, 0);
        border-right: 7px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 134px;
        position: absolute;
        top: -7px;    
    }
    .btn-group > ul.dropdown-menu:after {
        border-bottom: 6px solid #FFFFFF;
        border-left: 6px solid rgba(0, 0, 0, 0);
        border-right: 6px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 135px;
        position: absolute;
        top: -6px;        
    }
    @media (max-width: 980px) {
        .custresclass {
            float: none !important;
        }
    }
</style>

<?php    
    $menu = array('menu' => 'core_main_user');
    $notShow = array('core_main_profile', 'core_main_settings', 'core_main_user_task_list');
    echo $this->topMenuWidget(array('headtitle' => 'User Panel', 'menu' => $menu, 'notshow' => $notShow));
?>

<h4>
     <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
     <?php echo $this->translate('User Panel [Payment Invoice List]'); ?>
</h4>

<div style="clear: both;"></div>

<div class="span" style="margin-left: 0px;">
  <?php echo $this->formFilter->render($this); ?>
</div>

<div style="clear: both;"></div>

<div class="span item_results" style="margin-left: 0px;">
  <div class="item-found">
    <?php $count = $this->paginator->getTotalItemCount(); ?>
    <?php 
        if($count==1){
            echo $this->translate('Total %s payment invoice found.', $count);
        }else{
            echo $this->translate('Total %s payment invoices found.', $count);
        }
    ?>
    <?php if(false): ?>
      <div class="btn-toolbar custresclass" style="float: right;">
          <div class="btn-group">
              <a href="javascript:void(0)" class="btn" id="deleteSelected">
                  <i class="icon-remove"></i>
                  <?php echo $this->translate('Delete Selected'); ?>
              </a>
          </div>
      </div>
    <?php endif; ?>
  </div>
  <?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
      <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
      </div>
  <?php else: ?>
    <div style="clear: both;"></div><br />
  <?php endif; ?>
</div>

<?php if(count($this->paginator)): ?>
<div class="company-list span" style="margin-left: 0px;">
    <table class="list-table table table-bordered table-hover">
        <thead style="background-color: #c2cefb;">
            <tr>
                <th style="width: 15px;"><input type="checkbox" name="checkall" id="checkallitems" value="all" /></th>
                <th style="width: 75px;"><?php echo $this->translate('Reference'); ?></th>
                <th><?php echo $this->translate('Invoice Title'); ?></th>
                <th style="width: 245px;"><?php echo $this->translate('Ticket Details'); ?></th>
                <th style="width: 140px;"><?php echo $this->translate('Invoice Status'); ?></th>
                <th style="width: 120px;"><?php echo $this->translate('Options'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->paginator as $item): 
                $ticket = $item->getTicket();
                $member = $ticket->getUser();
                ?>
                <tr>
                    <td style="text-align: center;">
                        <input type="checkbox" name="checkit[]" class="checkeditems" value="<?php echo $item->getIdentity(); ?>" />
                    </td>
                    <td>
                        <a style="font-weight: bold;" href="<?php echo $this->url(array('action' => 'details', 'id' => $ticket->getIdentity()), 'user_tickets', true); ?>">
                            <?php echo $ticket->getReference(); ?>
                        </a>
                    </td>
                    <td>
                        <strong>Title:</strong> <?php echo $item->getTitle(); ?>
                        <strong>Amount Payable:</strong> <?php echo $item->getAmount(); ?>
                    </td>
                    <td>
                        <?php 
                        echo "<strong>Title:</strong> {$ticket->getTitle()}<br />";
                        echo "<strong>Raised By:</strong> <a href='{$this->url(array(), 'my_profile', true)}'>{$member->getTitle()}</a>";
                        ?>
                    </td>
                    <td><?php echo $item->getStatusWord(); ?></td>
                    <td style="text-align: center;">
                        <div class="btn-toolbar">
                           <div class="btn-group btn-group-horizontal">
                              <a href="<?php echo $this->url(array('action' => 'details', 'id' => $item->getIdentity()), 'user_invoices', true); ?>" class="btn" title="<?php echo $this->translate('View Details'); ?>">
                                  <i class="icon-eye-open"></i>
                              </a>
                           </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
    <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('#search').prepend("<i class='icon-search icon-white'></i> ");
$('#checkallitems').click(function(){
    $('.checkeditems').prop('checked', $(this).is(':checked'));
});
</script>