<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */

$invoice = $this->invoice;
$ticket = $invoice->getTicket();
$menu = array('menu' => 'core_main_user');
$notShow = array('core_main_profile', 'core_main_settings', 'core_main_user_task_list');
echo $this->topMenuWidget(array('headtitle' => 'User Panel', 'menu' => $menu, 'notshow' => $notShow));
?>

<div>
    <div id="formholder">
        <h4>
            <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
            <?php echo $this->translate('User Panel [Make Service Payment]'); ?>
        </h4>
        <div style="clear: both;"></div>
        <p style="margin: 25px 0px;">
            You are going to pay <strong><?php echo $invoice->getAmount(); ?></strong>
            to <strong>Heating System</strong> using credit card for taking support service on ticket
            reference #<a href="<?php echo $this->url(array('action' => 'details', 'id' => $ticket->getIdentity()), 'user_tickets', true); ?>"><strong><?php echo $ticket->getReference(); ?></strong></a>!
        </p>
        <div style="clear: both;"></div>
        <ul style="list-style: none; display: flex;">
            <li style="margin-right: 50px;"><img style="width: 200px;" src="<?php echo "{$this->baseUrl()}/public/images/visa.png"; ?>" /></li>
            <li><img style="width: 200px;" src="<?php echo "{$this->baseUrl()}/public/images/master.png"; ?>" /></li>
            <div style="clear: both;"></div>
        </ul>
        <br />
        <div style="clear: both;"></div>
        <?php echo $this->form->render($this); ?>
        <div style="clear: both;"></div>
    </div>
</div>

<script type="text/javascript">
$('#submit').prepend("<i class='icon-ok-sign icon-white'></i> ");
</script>
