<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */
?>

<style type="text/css">
    form#filter_form label {display: none;}
    .pagination {margin-top: 0px;}
    .custsubnav > li {text-align: left;}
    .btn-group > ul.dropdown-menu:before {
        border-bottom: 7px solid rgba(0, 0, 0, 0.2);
        border-left: 7px solid rgba(0, 0, 0, 0);
        border-right: 7px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 134px;
        position: absolute;
        top: -7px;    
    }
    .btn-group > ul.dropdown-menu:after {
        border-bottom: 6px solid #FFFFFF;
        border-left: 6px solid rgba(0, 0, 0, 0);
        border-right: 6px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 135px;
        position: absolute;
        top: -6px;        
    }
    @media (max-width: 980px) {
        .custresclass {
            float: none !important;
        }
    }
</style>

<?php 
    $menu = array('menu' => 'core_main_user');
    $notShow = array('core_main_profile', 'core_main_settings', 'core_main_user_task_list');
    echo $this->topMenuWidget(array('headtitle' => 'User Panel', 'menu' => $menu, 'notshow' => $notShow));
?>

<h4>
     <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
     <?php echo $this->translate('User Panel [Deleted Support Ticket List]'); ?>
</h4>

<div style="clear: both;"></div>

<div class="span" style="margin-left: 0px;">
  <?php echo $this->formFilter->render($this); ?>
</div>

<div style="clear: both;"></div>

<div class="span item_results" style="margin-left: 0px;">
  <div class="item-found">
    <?php $count = $this->paginator->getTotalItemCount(); ?>
    <?php 
        if($count==1){
            echo $this->translate('Total %s deleted support ticket found.', $count);
        }else{
            echo $this->translate('Total %s deleted support tickets found.', $count);
        }
    ?>
      <div class="btn-toolbar custresclass" style="float: right;">
          <div class="btn-group">
              <a href="<?php echo $this->url(array('action' => 'create'), 'user_tickets', true); ?>" class="btn">
                  <i class="icon-bullhorn"></i>
                  <?php echo $this->translate('Raise Support Ticket'); ?>
              </a>
              <a href="javascript:void(0)" class="btn" id="restoreSelected">
                  <i class="icon-refresh"></i>
                  <?php echo $this->translate('Restore Selected'); ?>
              </a>
              <a href="<?php echo $this->url(array('action' => 'trash'), 'user_tickets', true); ?>" class="btn active">
                  <i class="icon-trash"></i>
                  <?php echo $this->translate('Ticket Trash'); ?>
              </a>
          </div>
      </div>
  </div>
  <?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
      <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
      </div>
  <?php else: ?>
    <div style="clear: both;"></div><br />
  <?php endif; ?>
</div>

<?php if(count($this->paginator)): ?>
<div class="company-list span" style="margin-left: 0px;">
    <table class="list-table table table-bordered table-hover">
        <thead style="background-color: #c2cefb;">
            <tr>
                <th style="width: 15px;"><input type="checkbox" name="checkall" id="checkallitems" value="all" /></th>
                <th style="width: 120px;"><?php echo $this->translate('Ticket Reference'); ?></th>
                <th><?php echo $this->translate('Ticket Title'); ?></th>
                <th style="width: 115px;"><?php echo $this->translate('Ticket Priority'); ?></th>
                <th style="width: 110px;"><?php echo $this->translate('Ticket Status'); ?></th>
                <th style="width: 150px;"><?php echo $this->translate('Options'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->paginator as $item): ?>
                <tr>
                    <td style="text-align: center;">
                        <input type="checkbox" name="checkit[]" class="checkeditems" value="<?php echo $item->getIdentity(); ?>" />
                    </td>
                    <td>
                        <a style="font-weight: bold;" href="<?php echo $this->url(array('action' => 'details', 'id' => $item->getIdentity()), 'user_tickets', true); ?>">
                            <?php echo $item->getReference(); ?>
                        </a>
                    </td>
                    <td><?php echo $item->getTitle(); ?></td>
                    <td><?php echo $item->getPriorityWord(); ?></td>
                    <td><?php echo $item->getStatusWord(); ?></td>
                    <td style="text-align: center;">
                        <div class="btn-toolbar">
                           <div class="btn-group btn-group-horizontal">
                              <a href="javascript:void(0)" onclick="javascript:restoreThis(<?php echo $item->getIdentity(); ?>)" class="btn" title="<?php echo $this->translate('Restore'); ?>">
                                  <i class="icon-refresh"></i>
                              </a>
                           </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
    <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('#search').prepend("<i class='icon-search icon-white'></i> ");
$('#checkallitems').click(function(){
    $('.checkeditems').prop('checked', $(this).is(':checked'));
});
$('#restoreSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to restore the selected tickets?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });
        
        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'restore'), 'user_tickets', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any ticket!'); ?>');
        }
    }
});
function restoreThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to restore the ticket?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'restore'), 'user_tickets', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
</script>