<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */
?>

<style type="text/css">
    form#filter_form label {display: none;}
    .pagination {margin-top: 0px;}
    .custsubnav > li {text-align: left;}
    .btn-group > ul.dropdown-menu:before {
        border-bottom: 7px solid rgba(0, 0, 0, 0.2);
        border-left: 7px solid rgba(0, 0, 0, 0);
        border-right: 7px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 134px;
        position: absolute;
        top: -7px;    
    }
    .btn-group > ul.dropdown-menu:after {
        border-bottom: 6px solid #FFFFFF;
        border-left: 6px solid rgba(0, 0, 0, 0);
        border-right: 6px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 135px;
        position: absolute;
        top: -6px;        
    }
    @media (max-width: 980px) {
        .custresclass {
            float: none !important;
        }
    }
</style>

<?php 
    $menu = array('menu' => 'core_main_user');
    $notShow = array('core_main_profile', 'core_main_settings', 'core_main_user_task_list');
    echo $this->topMenuWidget(array('headtitle' => 'User Panel', 'menu' => $menu, 'notshow' => $notShow));
?>

<h4>
     <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
     <?php echo $this->translate('User Panel [Support Ticket List]'); ?>
</h4>

<div style="clear: both;"></div>

<div class="span" style="margin-left: 0px;">
  <?php echo $this->formFilter->render($this); ?>
</div>

<div style="clear: both;"></div>

<div class="span item_results" style="margin-left: 0px;">
  <div class="item-found">
    <?php $count = $this->paginator->getTotalItemCount(); ?>
    <?php 
        if($count==1){
            echo $this->translate('Total %s support ticket found.', $count);
        }else{
            echo $this->translate('Total %s support tickets found.', $count);
        }
    ?>
      <div class="btn-toolbar custresclass" style="float: right;">
          <div class="btn-group">
              <a href="javascript:void(0)" class="btn" id="closeSelected">
                  <i class="icon-off"></i>
                  <?php echo $this->translate('Close Selected'); ?>
              </a>
              <a href="javascript:void(0)" class="btn" id="deleteSelected">
                  <i class="icon-remove"></i>
                  <?php echo $this->translate('Delete Selected'); ?>
              </a>
              <a href="javascript:void(0)" class="btn" id="reopenSelected">
                  <i class="icon-refresh"></i>
                  <?php echo $this->translate('Reopen Selected'); ?>
              </a>
          </div>
      </div>
  </div>
  <?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
      <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
      </div>
  <?php else: ?>
    <div style="clear: both;"></div><br />
  <?php endif; ?>
</div>

<?php if(count($this->paginator)): ?>
<div class="company-list span" style="margin-left: 0px;">
    <table class="list-table table table-bordered table-hover">
        <thead style="background-color: #c2cefb;">
            <tr>
                <th style="width: 15px;"><input type="checkbox" name="checkall" id="checkallitems" value="all" /></th>
                <th style="width: 120px;"><?php echo $this->translate('Ticket Reference'); ?></th>
                <th><?php echo $this->translate('Ticket Title'); ?></th>
                <th style="width: 115px;"><?php echo $this->translate('Ticket Priority'); ?></th>
                <th style="width: 120px;"><?php echo $this->translate('Ticket Status'); ?></th>
                <th style="width: 150px;"><?php echo $this->translate('Options'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->paginator as $item): ?>
                <tr>
                    <td style="text-align: center;">
                        <input type="checkbox" name="checkit[]" class="checkeditems" value="<?php echo $item->getIdentity(); ?>" />
                    </td>
                    <td>
                        <a style="font-weight: bold;" href="<?php echo $this->url(array('action' => 'details', 'id' => $item->getIdentity()), 'user_tickets', true); ?>">
                            <?php echo $item->getReference(); ?>
                        </a>
                    </td>
                    <td>
                        <?php 
                        echo "<strong>{$item->getTitle()}</strong><br />";
                        if($item->isScheduled()){
                            $schedule = $item->getSchedule();
                            echo "<strong>Scheduled Date:</strong> {$schedule->scheduled_date}<br />";
                            echo "<strong>Starting Time:</strong> {$schedule->from_time}<br />";
                            echo "<strong>Finishing Time:</strong> {$schedule->to_time}<br />";
                        }                            
                        ?>
                    </td>
                    <td><?php echo $item->getPriorityWord(); ?></td>
                    <td>
                        <?php 
                        if($item->isResolved()){echo "{$item->getResolvedWord()}<br />";}
                        if($item->isScheduled() && in_array($item->status, array(1, 4))){
                            echo $item->getScheduledWord(); 
                        }else{
                            echo $item->getStatusWord(); 
                        }
                        if(!$item->isResolved()){echo "<br />{$item->getResolvedWord()}";}
                        ?>
                    </td>
                    <td style="text-align: center;">
                        <div class="btn-toolbar">
                           <div class="btn-group btn-group-horizontal">
                              <a href="<?php echo $this->url(array('action' => 'details', 'id' => $item->getIdentity()), 'user_tickets', true); ?>" class="btn" title="<?php echo $this->translate('View Details'); ?>">
                                  <i class="icon-eye-open"></i>
                              </a>
                              <a href="javascript:void(0)" onclick="javascript:deleteThis(<?php echo $item->getIdentity(); ?>)" class="btn" title="<?php echo $this->translate('Delete'); ?>">
                                  <i class="icon-remove"></i>
                              </a>
                              <a href="javascript:void(0)" class="btn dropdown-toggle" data-toggle="dropdown" title="<?php echo $this->translate('Action List'); ?>">
                                  <i class="icon-list"></i>
                              </a>
                              <ul class="dropdown-menu pull-right custsubnav">
                                  <?php if(!$item->isScheduled()): ?>
                                 <li>
                                     <a href="<?php echo $this->url(array('action' => 'priority', 'id' => $item->getIdentity()), 'user_tickets', true); ?>">
                                         <i class="icon-edit"></i>
                                         <?php echo $this->translate('Change Priority'); ?>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0)" onclick="javascript:closeThis(<?php echo $item->getIdentity(); ?>)">
                                         <i class="icon-off"></i>
                                         <?php echo $this->translate('Close Ticket'); ?>
                                     </a>
                                 </li>                                 
                                 <li>
                                     <a href="javascript:void(0)" onclick="javascript:reopenThis(<?php echo $item->getIdentity(); ?>)">
                                         <i class="icon-repeat"></i>
                                         <?php echo $this->translate('Reopen Ticket'); ?>
                                     </a>
                                 </li>   
                                 <?php endif; ?>
                                 <?php if($item->isResolved()): ?>
                                 <li>
                                     <a href="javascript:void(0)" onclick="javascript:reopenThis(<?php echo $item->getIdentity(); ?>)">
                                         <i class="icon-repeat"></i>
                                         <?php echo $this->translate('Reopen Ticket'); ?>
                                     </a>
                                 </li>   
                                 <?php endif; ?>
                                 <?php if($item->canMakePayment()): ?>
                                 <li>
                                     <a href="<?php echo $this->url(array('action' => 'details', 'id' =>$item->invoice_id), 'user_invoices', true); ?>">
                                         <i class="icon-list-alt"></i>
                                         <?php echo $this->translate('View Invoice'); ?>
                                     </a>
                                 </li>                                 
                                 <?php endif; ?>
                              </ul>                               
                           </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
    <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('#search').prepend("<i class='icon-search icon-white'></i> ");
$('#checkallitems').click(function(){
    $('.checkeditems').prop('checked', $(this).is(':checked'));
});
$('#deleteSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to delete the selected tickets?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });
        
        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'delete'), 'user_tickets', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any ticket!'); ?>');
        }
    }
});
$('#closeSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to close the selected tickets?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });
        
        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'close'), 'user_tickets', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any ticket!'); ?>');
        }
    }
});
$('#reopenSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to reopen the selected tickets?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });
        
        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'reopen'), 'user_tickets', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any ticket!'); ?>');
        }
    }
});
function deleteThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to delete the ticket?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'delete'), 'user_tickets', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
function closeThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to close the ticket?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'close'), 'user_tickets', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
function reopenThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to reopen the ticket?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'reopen'), 'user_tickets', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
</script>