<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */
?>

<div class="hero-unit" style="padding: 100px 60px; margin-bottom: 0px;">
    <h1 style="text-align: center;">
        [Admin Panel]
        <br />
        Web Application
        <br />
        for
        <br />
        Heating System!
    </h1>
</div>