<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */

$viewer = $this->viewer();
$identity = $this->identity;
$navigation = $this->navigation;
?>

<div class="navbar-inner">
    <div class="container-fluid">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".navminimenu">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="brand" href="<?php echo $this->url(array(), 'landing_home', true); ?>">
            <?php echo $this->translate('Heating System'); ?>
        </a>
        <div class="nav-collapse collapse navminimenu">
            <p class="navbar-text pull-right">
                <?php
                    if($viewer){
                        echo $this->translate('Logged in as %s', "<a href='{$viewer->getHref()}' class='navbar-link'>{$viewer->getTitle()}</a>");
                    }
                ?>
            </p>
            <ul class="nav">
            <?php foreach($navigation as $menu){
                $params = $menu->getParams();
                $active = in_array($identity, $menu->getPage()) ? true : false;
                ?>
                <li<?php if($active){echo " class='active'";} ?>>
                    <a href="<?php echo $this->url($params['params'], $params['route'], true); ?>">
                        <?php
                        $menuIcon = $menu->getIcon();
                        if(!empty($menuIcon)){ ?>
                            <i class="<?php echo $menuIcon; ?> icon-white"></i>
                        <?php } ?>
                        <?php echo $this->translate($menu->getLabel()); ?>
                    </a>
                </li>
            <?php } ?>
            </ul>
        </div>
    </div>
</div>
