<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */

$viewer = $this->viewer();
if(false && count($this->paginator)):
?>


<style type="text/css">
    form#filter_form label {display: none;}
    .pagination {margin-top: 0px;}
    .custsubnav > li {text-align: left;}
    table.list-table tr {cursor: pointer; font-weight: bold;}
    table.list-table tr ul {
        color: #333333;
 	margin: 10px 0px 0px 0px;
	font-weight: bold;
	background-color: #ededed;
	padding: 8px 0px 8px 25px;
    }
    table.list-table tr ul li div {min-width: 200px; display: inline-flex;}
    .btn-group > ul.dropdown-menu:before {
        border-bottom: 7px solid rgba(0, 0, 0, 0.2);
        border-left: 7px solid rgba(0, 0, 0, 0);
        border-right: 7px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 134px;
        position: absolute;
        top: -7px;
    }
    .btn-group > ul.dropdown-menu:after {
        border-bottom: 6px solid #FFFFFF;
        border-left: 6px solid rgba(0, 0, 0, 0);
        border-right: 6px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 135px;
        position: absolute;
        top: -6px;
    }
    @media (max-width: 980px) {
        .custresclass {
            float: none !important;
        }
    }
</style>

<?php
     $menu = array('menu' => 'admin_top_menu');
     echo $this->topMenuWidget(array('headtitle' => 'Dashboard', 'menu' => $menu));
?>

<h4>
     <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
     <?php echo $this->translate('Application Dashboard [Sea-Port Selection Result For Vessels]'); ?>
</h4>

<div style="clear: both;"></div>

<div class="span item_results" style="margin-left: 0px;">
  <div class="item-found">
    <?php $count = $this->paginator->getTotalItemCount(); ?>
    <?php
        if($count==1){
            echo $this->translate('Total %s result found.', $count);
        }else{
            echo $this->translate('Total %s results found.', $count);
        }
    ?>
      <div class="btn-toolbar custresclass" style="float: right;">
          <div class="btn-group">
              <a href="<?php echo $this->url(array('action' => 'export'), 'landing_home', true); ?>" class="btn">
                  <i class="icon-download-alt"></i>
                  <?php echo $this->translate('Export Result Sheet'); ?>
              </a>
              <?php //if($viewer): ?>
              <a href="<?php echo $this->url(array('action' => 'calculate'), 'admin_port_general', true); ?>" class="btn">
                  <i class="icon-tasks"></i>
                  <?php echo $this->translate('Calculate Sea-Port'); ?>
              </a>
              <a href="javascript:void(0)" class="btn" id="deleteSelected">
                  <i class="icon-trash"></i>
                  <?php echo $this->translate('Delete Result Data'); ?>
              </a>
              <?php //endif; ?>
          </div>
      </div>
  </div>
  <?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
      <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array()); ?>
      </div>
  <?php endif; ?>
</div>

<?php if(count($this->paginator)): ?>

<div style="clear: both;"></div>
<div style="margin: 35px 0px;">
    <?php echo $this->portPopularityColumnWidget($this->portCountArray, 1); ?>
</div>
<div style="clear: both;"></div>

<div class="company-list span" style="margin-left: 0px;">
    <table class="list-table table table-bordered table-hover">
        <thead>
            <tr style="background-color: #eee;">
                <th style="width: 200px;"><?php echo $this->translate('Vessel Name'); ?></th>
                <th><?php echo $this->translate('Sea-Port Name'); ?></th>
                <th style="width: 110px;"><?php echo $this->translate('Highest Score'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $counter = 1;
            foreach($this->paginator as $vesselName => $vesselData): ?>
                <tr title="<?php echo $this->translate('Click on the row to see details.'); ?>">
                    <td style="font-weight: bold; background-color: #eee;"><?php echo ucwords($this->translate($vesselName)); ?></td>
                    <?php foreach($vesselData as $portName => $highScore): ?>
                        <td>
                            <?php echo $portName; ?>
                            <?php 
                                $details = $this->dataCalculated[$vesselName]; 
                                arsort($details);
                            ?>
                            <ul style="display: none;">
                                <h4 style="margin-left: -12px;">
                                    <?php echo $this->translate('Result Details'); ?>:
                                    <?php echo $this->chartPerShipWidget($this->dataCalculated[$vesselName], $vesselName, $counter); ?>
                                </h4>
                                <?php foreach($details as $portName2 => $highScore2): ?>
                                <li><?php echo "<div>{$portName2}</div><div>: {$highScore2}</div>"; ?><span style="clear: both;"></span></li>
                                <?php endforeach; ?>
                            </ul>
                        </td>
                        <td><?php echo $highScore; ?></td>
                    <?php endforeach; ?>
                </tr>
            <?php $counter++; endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
    <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array()); ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('#deleteSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to delete result data?'); ?>')){
        location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_dashboard', true); ?>";
    }
});
$('table.list-table tr').click(function(){
    if($(this).find('ul').css('display') == 'none'){
        $(this).find('ul').show('fast', function(){
            $(this).parent('td').css({'background-color': '#083838', 'color': '#ffffff'});
        })
    }else if($(this).find('ul').css('display') != 'none'){
        $(this).find('ul').hide('fast', function(){
            $(this).parent('td').css({'background-color': '', 'color': ''});
        })
    }
});
</script>
<?php endif; ?>

<?php if(true || !count($this->paginator)): ?>
<div class="hero-unit" style="padding: 135px 60px; margin-bottom: 0px;">
    <h1 style="text-align: center;">
        Web Application
        <br />
        for
        <br />
        Heating System!
    </h1>
</div>
<?php endif; ?>