<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */

$ticket = $this->ticket;
$viewer = $this->viewer();
$menu = array('menu' => "core_main_{$viewer->getUserType()}_ticket_top");
echo $this->topMenuWidget(array('headtitle' => 'Admin Panel', 'menu' => $menu));
?>

<div style="clear: both;"></div>

<div class="hero-unit" style="width: 96%; padding: 10px 20px; margin-bottom: 0px;">
    <h4>
        <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
        <?php echo $this->translate('Admin Panel [Support Ticket Details]'); ?>
    </h4>
    <div style="clear: both;"></div>
    <div class="btn-toolbar custresclass" style="float: right;">
        <div class="btn-group">
            <?php if(!$ticket->user_delete): ?>
            <a href="<?php echo $this->url(array('action' => 'priority', 'id' => $ticket->getIdentity()), 'user_tickets', true); ?>" class="btn">
                <i class="icon-edit"></i>
                <?php echo $this->translate('Change Priority'); ?>
            </a>
            <a href="javascript:void(0)" onclick="javascript:closeThis(<?php echo $ticket->getIdentity(); ?>)" class="btn">
                <i class="icon-off"></i>
                <?php echo $this->translate('Close Ticket'); ?>
            </a>
            <a href="javascript:void(0)" onclick="javascript:deleteThis(<?php echo $ticket->getIdentity(); ?>)" class="btn">
                <i class="icon-remove"></i>
                <?php echo $this->translate('Delete Ticket'); ?>
            </a>
            <a href="javascript:void(0)" onclick="javascript:reopenThis(<?php echo $ticket->getIdentity(); ?>)" class="btn">
                <i class="icon-refresh"></i>
                <?php echo $this->translate('Reopen Ticket'); ?>
            </a>
            <?php else: ?>
            <a href="javascript:void(0)" onclick="javascript:restoreThis(<?php echo $ticket->getIdentity(); ?>)" class="btn">
                <i class="icon-refresh"></i>
                <?php echo $this->translate('Restore Ticket'); ?>
            </a>
            <?php endif; ?>
        </div>
    </div>
    <div style="clear: both;"></div>
    <br />
    <p style="color: #000;"><strong>Title: <?php echo $ticket->getTitle(); ?></strong></p>    
    <p style="color: #000;"><strong>Status:</strong> <?php echo $ticket->getStatusWord(); ?></p>
    <p style="color: #000;"><strong>Priority:</strong> <?php echo $ticket->getPriorityWord(); ?></p>
    <p style="color: #000;"><strong>Description:</strong> <?php echo $ticket->getDescription(); ?></p>
</div>

<?php if(!$ticket->user_delete): ?>
<script type="text/javascript">
function deleteThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to delete the ticket?'); ?>')){
        if($itemId != ''){
            location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_tickets', true); ?>/id/"+$itemId+"/pg/0";
        }
    }
}
function closeThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to close the ticket?'); ?>')){
        if($itemId != ''){
            location.href = "<?php echo $this->url(array('action' => 'close'), 'admin_tickets', true); ?>/id/"+$itemId+"/pg/0";
        }
    }
}
function reopenThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to reopen the ticket?'); ?>')){
        if($itemId != ''){
            location.href = "<?php echo $this->url(array('action' => 'reopen'), 'admin_tickets', true); ?>/id/"+$itemId+"/pg/0";
        }
    }
}
</script>
<?php else: ?>
<script type="text/javascript">
function restoreThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to restore the ticket?'); ?>')){
        if($itemId != ''){
            location.href = "<?php echo $this->url(array('action' => 'restore'), 'admin_tickets', true); ?>/id/"+$itemId+"/pg/0";
        }
    }
}
</script>
<?php endif; ?>