<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */
?>

<style type="text/css">
    form#filter_form label {display: none;}
    .pagination {margin-top: 0px;}
    .custsubnav > li {text-align: left;}
    .btn-group > ul.dropdown-menu:before {
        border-bottom: 7px solid rgba(0, 0, 0, 0.2);
        border-left: 7px solid rgba(0, 0, 0, 0);
        border-right: 7px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 134px;
        position: absolute;
        top: -7px;    
    }
    .btn-group > ul.dropdown-menu:after {
        border-bottom: 6px solid #FFFFFF;
        border-left: 6px solid rgba(0, 0, 0, 0);
        border-right: 6px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 135px;
        position: absolute;
        top: -6px;        
    }
    @media (max-width: 980px) {
        .custresclass {
            float: none !important;
        }
    }
</style>

<?php 
    $viewer = $this->viewer();
    $menu = array('menu' => "core_main_{$viewer->getUserType()}_task_top");
    echo $this->topMenuWidget(array('headtitle' => 'Admin Panel', 'menu' => $menu));
?>

<h4>
     <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
     <?php echo $this->translate('Admin Panel [Scheduled Tasks List]'); ?>
</h4>

<div style="clear: both;"></div>

<div class="span" style="margin-left: 0px;">
  <?php echo $this->formFilter->render($this); ?>
</div>

<div style="clear: both;"></div>

<div class="span item_results" style="margin-left: 0px;">
  <div class="item-found">
    <?php $count = $this->paginator->getTotalItemCount(); ?>
    <?php 
        if($count==1){
            echo $this->translate('Total %s service schedule found.', $count);
        }else{
            echo $this->translate('Total %s service schedules found.', $count);
        }
    ?>
      <div class="btn-toolbar custresclass" style="float: right;">
          <div class="btn-group">
              <a href="javascript:void(0)" class="btn" id="closeSelected">
                  <i class="icon-off"></i>
                  <?php echo $this->translate('Close Selected Schedules'); ?>
              </a>
              <a href="javascript:void(0)" class="btn" id="deleteSelected">
                  <i class="icon-remove"></i>
                  <?php echo $this->translate('Delete Selected Schedules'); ?>
              </a>
              <?php if(false): ?>
              <a href="javascript:void(0)" class="btn" id="reopenSelected">
                  <i class="icon-refresh"></i>
                  <?php echo $this->translate('Reopen Selected'); ?>
              </a>
              <?php endif; ?>
          </div>
      </div>      
  </div>
  <?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
      <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
      </div>
  <?php else: ?>
    <div style="clear: both;"></div><br />
  <?php endif; ?>
</div>

<?php if(count($this->paginator)): ?>
<div class="company-list span" style="margin-left: 0px;">
    <table class="list-table table table-bordered table-hover">
        <thead style="background-color: #c2cefb;">
            <tr>
                <th style="width: 15px;"><input type="checkbox" name="checkall" id="checkallitems" value="all" /></th>
                <th style="width: 175px;"><?php echo $this->translate('Ticket Details'); ?></th>
                <th><?php echo $this->translate('Customer Details'); ?></th>
                <th style="width: 178px;"><?php echo $this->translate('Technician Details'); ?></th>
                <th style="width: 120px;"><?php echo $this->translate('Status'); ?></th>
                <th style="width: 140px;"><?php echo $this->translate('Options'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->paginator as $item): 
                $ticket = $item->getTicket();
                $member = $item->getMember();
                $technician = $item->getTechnician();
                ?>
                <tr>
                    <td style="text-align: center;">
                        <input type="checkbox" name="checkit[]" class="checkeditems" value="<?php echo $item->getIdentity(); ?>" />
                    </td>
                    <td>
                        <a style="font-weight: bold;" href="<?php echo $this->url(array('action' => 'details', 'id' => $ticket->getIdentity()), 'admin_tickets', true); ?>">
                            Reference: #<?php echo $ticket->getReference(); ?>
                        </a>
                        <br />
                        Ticket: <?php echo $ticket->getTitle(); ?>
                        <br />
                        Schedule Date: <?php echo $item->scheduled_date; ?>
                        <br />
                        Starting Time: <?php echo $item->from_time; ?>
                        <br />
                        Finishing Time: <?php echo $item->to_time; ?>
                    </td>
                    <td>
                        <a style="font-weight: bold;" href="<?php echo $this->url(array('action' => 'details', 'id' => $member->getIdentity()), 'admin_users', true); ?>">
                            <?php echo $member->getTitle(); ?>
                        </a>                        
                        <br />
                        <?php echo "<strong>Phone:</strong> {$member->phone_no}"; ?>
                        <br />
                        <?php echo "<strong>Mobile:</strong> {$member->mobile_no}"; ?>
                        <br />
                        <?php echo "<strong>Address:</strong> {$member->getAddress()}"; ?>
                    </td>
                    <td>                        
                        <a style="font-weight: bold;" href="<?php echo $this->url(array('action' => 'details', 'id' => $technician->getIdentity()), 'admin_users', true); ?>">
                            <?php echo $technician->getTitle(); ?>
                        </a>                        
                        <br />
                        <?php echo "<strong>Phone:</strong> {$technician->phone_no}"; ?>
                        <br />
                        <?php echo "<strong>Mobile:</strong> {$technician->mobile_no}"; ?>
                        <br />
                        <?php echo "<strong>Address:</strong> {$technician->getAddress()}"; ?>
                    </td>
                    <td><?php echo $item->getStatusWord(); ?></td>
                    <td style="text-align: center;">                        
                        <div class="btn-toolbar">
                           <div class="btn-group btn-group-horizontal">
                              <a href="<?php echo $this->url(array('action' => 'details', 'id' => $ticket->getIdentity()), 'admin_tickets', true); ?>" class="btn" title="<?php echo $this->translate('View Details'); ?>">
                                  <i class="icon-eye-open"></i>
                              </a>
                              <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item->getIdentity()), 'admin_tasks', true); ?>"  class="btn" title="<?php echo $this->translate('Edit Schedule'); ?>">
                                  <i class="icon-edit"></i>
                              </a>
                              <a href="javascript:void(0)" class="btn dropdown-toggle" data-toggle="dropdown" title="<?php echo $this->translate('Action List'); ?>">
                                  <i class="icon-list"></i>
                              </a>
                              <ul class="dropdown-menu pull-right custsubnav">
                                 <li>
                                     <a href="javascript:void(0)" onclick="javascript:closeThis(<?php echo $item->getIdentity(); ?>)">
                                         <i class="icon-off"></i>
                                         <?php echo $this->translate('Close Schedule'); ?>
                                     </a>
                                 </li>
                                 <li>
                                     <a href="javascript:void(0)" onclick="javascript:deleteThis(<?php echo $item->getIdentity(); ?>)">
                                         <i class="icon-remove"></i>
                                         <?php echo $this->translate('Delete Schedule'); ?>
                                     </a>
                                 </li>
                              </ul>                               
                           </div>
                        </div>                        
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
    <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('#search').prepend("<i class='icon-search icon-white'></i> ");
$('#checkallitems').click(function(){
    $('.checkeditems').prop('checked', $(this).is(':checked'));
});
$('#closeSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to close the selected schedules?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });
        
        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'close'), 'admin_tasks', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any schedule!'); ?>');
        }
    }
});
$('#deleteSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to delete the selected schedules?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });
        
        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_tasks', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any schedule!'); ?>');
        }
    }
});
function closeThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to close the schedule?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'close'), 'admin_tasks', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
function deleteThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to delete the schedule?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_tasks', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
</script>