<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */
?>

<style type="text/css">
    form#filter_form label {display: none;}
    .pagination {margin-top: 0px;}
    .custsubnav > li {text-align: left;}
    .btn-group > ul.dropdown-menu:before {
        border-bottom: 7px solid rgba(0, 0, 0, 0.2);
        border-left: 7px solid rgba(0, 0, 0, 0);
        border-right: 7px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 134px;
        position: absolute;
        top: -7px;
    }
    .btn-group > ul.dropdown-menu:after {
        border-bottom: 6px solid #FFFFFF;
        border-left: 6px solid rgba(0, 0, 0, 0);
        border-right: 6px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 135px;
        position: absolute;
        top: -6px;
    }
    @media (max-width: 980px) {
        .custresclass {
            float: none !important;
        }
    }
</style>

<?php
     $menu = array('menu' => 'admin_top_menu');
     echo $this->topMenuWidget(array('headtitle' => 'Admin', 'menu' => $menu));
?>

<h4>
     <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
     <?php echo $this->translate('Admin Panel [Page List]'); ?>
</h4>

<div style="clear: both;"></div>

<div class="span item_results" style="margin-left: 0px;">
  <div class="item-found">
    <?php $count = $this->paginator->getTotalItemCount(); ?>
    <?php
        if($count==1){
            echo $this->translate('Total %s page found.', $count);
        }else{
            echo $this->translate('Total %s pages found.', $count);
        }
    ?>
      <div class="btn-toolbar custresclass" style="float: right;">
          <div class="btn-group">
              <a href="<?php echo $this->url(array('action' => 'add'), 'admin_page_general', true); ?>" class="btn">
                  <i class="icon-plus-sign"></i>
                  <?php echo $this->translate('Add New Page'); ?>
              </a>
              <a href="javascript:void(0)" class="btn" id="deleteSelected">
                  <i class="icon-trash"></i>
                  <?php echo $this->translate('Delete Selected'); ?>
              </a>
          </div>
      </div>
  </div>
  <?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
      <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array()); ?>
      </div>
  <?php endif; ?>
</div>

<?php if(count($this->paginator)): ?>
<div class="company-list span" style="margin-left: 0px;">
    <table class="list-table table table-bordered table-hover">
        <thead>
            <tr>
                <th>
                    <input type="checkbox" name="checkall" id="checkallitems" value="all" />
                </th>
                <th><?php echo $this->translate('Page Info'); ?></th>
                <th style="width: 225px;"><?php echo $this->translate('Meta Keywords'); ?></th>
                <th style="width: 180px;"><?php echo $this->translate('Meta Description'); ?></th>
                <th style="width: 150px;"><?php echo $this->translate('Modified Date'); ?></th>
                <th style="width: 50px;"><?php echo $this->translate('Options'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->paginator as $item): ?>
                <tr>
                    <td style="text-align: center;">
                        <input type="checkbox" name="checkit[]" class="checkeditems" value="<?php echo $item->getIdentity(); ?>" />
                    </td>
                    <td>
                        <?php
                            echo $this->translate('Page Title: %s', $item->getTitle());
                            echo "<br />";
                            echo $this->translate('Page Name: %s', $item->getPageName());
                        ?>
                    </td>
                    <td><?php echo $item->getMetaKeys(); ?></td>
                    <td><?php echo $item->getMetaDesc(); ?></td>
                    <td><?php echo $item->modifiedDate(); ?></td>
                    <td style="text-align: center;">
                        <div class="btn-toolbar">
                           <div class="btn-group btn-group-vertical">
                              <a href="<?php echo $this->url(array('action' => 'edit', 'id' => $item->getIdentity()), 'admin_page_action', true); ?>" class="btn" title="<?php echo $this->translate('Edit'); ?>">
                                  <i class="icon-edit"></i>
                              </a>
                              <a href="javascript:void(0)" onclick="javascript:deleteThis(<?php echo $item->getIdentity(); ?>)" class="btn" title="<?php echo $this->translate('Delete'); ?>">
                                  <i class="icon-trash"></i>
                              </a>
                           </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
    <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array()); ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('#checkallitems').click(function(){
    $('.checkeditems').prop('checked', $(this).is(':checked'));
});
$('#deleteSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to delete the selected pages?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });

        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_page_general', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any page!'); ?>');
        }
    }
});
function deleteThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to delete the page?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'delete'), 'admin_page_general', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
</script>
