<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */
?>

<style type="text/css">
    form#filter_form label {display: none;}
    .pagination {margin-top: 0px;}
    .custsubnav > li {text-align: left;}
    .btn-group > ul.dropdown-menu:before {
        border-bottom: 7px solid rgba(0, 0, 0, 0.2);
        border-left: 7px solid rgba(0, 0, 0, 0);
        border-right: 7px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 134px;
        position: absolute;
        top: -7px;    
    }
    .btn-group > ul.dropdown-menu:after {
        border-bottom: 6px solid #FFFFFF;
        border-left: 6px solid rgba(0, 0, 0, 0);
        border-right: 6px solid rgba(0, 0, 0, 0);
        content: "";
        display: inline-block;
        left: 135px;
        position: absolute;
        top: -6px;        
    }
    @media (max-width: 980px) {
        .custresclass {
            float: none !important;
        }
    }
</style>

<?php 
    $viewer = $this->viewer();
    $menu = array('menu' => "core_main_{$viewer->getUserType()}_user_top");
    echo $this->topMenuWidget(array('headtitle' => 'Admin Panel', 'menu' => $menu));
?>

<h4>
     <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
     <?php echo $this->translate('Admin Panel [List of Technicians]'); ?>
</h4>

<div style="clear: both;"></div>

<div class="span" style="margin-left: 0px;">
  <?php echo $this->formFilter->render($this); ?>
</div>

<div style="clear: both;"></div>

<div class="span item_results" style="margin-left: 0px;">
  <div class="item-found">
    <?php $count = $this->paginator->getTotalItemCount(); ?>
    <?php 
        if($count==1){
            echo $this->translate('Total %s active technician found.', $count);
        }else{
            echo $this->translate('Total %s active technicians found.', $count);
        }
    ?>
      <div class="btn-toolbar custresclass" style="float: right;">
          <div class="btn-group">
              <a href="javascript:void(0)" class="btn" id="inactivateSelected">
                  <i class="icon-off"></i>
                  <?php echo $this->translate('Inactivate Selected Technicians'); ?>
              </a>
              <a href="javascript:void(0)" class="btn" id="deleteSelectedTechnician">
                  <i class="icon-remove"></i>
                  <?php echo $this->translate('Delete Selected Technicians'); ?>
              </a>
          </div>
      </div>
  </div>
  <?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
      <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
      </div>
  <?php else: ?>
    <div style="clear: both;"></div><br />
  <?php endif; ?>
</div>

<?php if(count($this->paginator)): ?>
<div class="company-list span" style="margin-left: 0px;">
    <table class="list-table table table-bordered table-hover">
        <thead style="background-color: #c2cefb;">
            <tr>
                <th style="width: 15px;"><input type="checkbox" name="checkall" id="checkallitems" value="all" /></th>
                <th style="width: 265px;"><?php echo $this->translate('Fullname & Contact'); ?></th>
                <th><?php echo $this->translate('Address & Location'); ?></th>
                <th style="width: 115px;"><?php echo $this->translate('IP, Lat & Lng'); ?></th>
                <th style="width: 125px;"><?php echo $this->translate('Technician Status'); ?></th>
                <th style="width: 110px;"><?php echo $this->translate('Options'); ?></th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->paginator as $item): ?>
                <tr>
                    <td style="text-align: center;">
                        <input type="checkbox" name="checkit[]" class="checkeditems" value="<?php echo $item->getIdentity(); ?>" />
                    </td>
                    <td>
                        <a style="font-weight: bold;" href="<?php echo $this->url(array('action' => 'details', 'id' => $item->getIdentity()), 'admin_users', true); ?>">
                            <?php echo $item->getTitle(); ?>
                        </a>
                        <?php 
                            echo "<br />Email: <a href='mailto:{$item->getEmail()}'>{$item->getEmail()}</a><br />"; 
                            echo "Phone: {$item->phone_no}<br />"; 
                            echo "Mobile: {$item->mobile_no}"; 
                        ?>
                    </td>
                    <td>
                        <?php echo $item->getAddress(); ?>
                    </td>
                    <td>
                        <?php 
                            echo "IP: {$item->ipaddress}<br />"; 
                            echo "Lat: {$item->latitude}<br />"; 
                            echo "Lng: {$item->longitude}"; 
                        ?>
                    </td>
                    <td><?php echo $item->isActiveWord(); ?></td>
                    <td style="text-align: center;">
                        <div class="btn-toolbar">
                           <div class="btn-group btn-group-horizontal">
                              <a href="<?php echo $this->url(array('action' => 'details', 'id' => $item->getIdentity()), 'admin_users', true); ?>" class="btn" title="<?php echo $this->translate('View Details'); ?>">
                                  <i class="icon-eye-open"></i>
                              </a>
                              <a href="javascript:void(0)" onclick="javascript:deleteTechnician(<?php echo $item->getIdentity(); ?>)" class="btn" title="<?php echo $this->translate('Delete Technician'); ?>">
                                  <i class="icon-remove"></i>
                              </a>
                              <a href="javascript:void(0)" class="btn dropdown-toggle" data-toggle="dropdown" title="<?php echo $this->translate('Action List'); ?>">
                                  <i class="icon-list"></i>
                              </a>
                              <ul class="dropdown-menu pull-right custsubnav">
                                 <li>
                                     <a href="javascript:void(0)" onclick="javascript:inactivateThis(<?php echo $item->getIdentity(); ?>)">
                                         <i class="icon-off"></i>
                                         <?php echo $this->translate('Inactivate'); ?>
                                     </a>
                                 </li>                                 
                              </ul>                               
                           </div>
                        </div>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php endif; ?>

<?php if($this->paginator->getTotalItemCount() > $this->itemPerPage): ?>
    <div>
        <?php echo $this->paginationControl($this->paginator, null, null, array(
          'pageAsQuery' => true,
          'query' => $this->formValues
        )); ?>
    </div>
<?php endif; ?>

<script type="text/javascript">
$('#search').prepend("<i class='icon-search icon-white'></i> ");
$('#checkallitems').click(function(){
    $('.checkeditems').prop('checked', $(this).is(':checked'));
});
$('#inactivateSelected').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to inactivate the selected technicians?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });
        
        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'inactivate'), 'admin_users', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any technician!'); ?>');
        }
    }
});
function inactivateThis($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to inactivate the technician?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'inactivate'), 'admin_users', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
$('#deleteSelectedTechnician').click(function(){
    if(confirm('<?php echo $this->translate('Are you sure to delete the selected technicians?'); ?>')){
        var $count = 0;
        var $selectedItems = new Array();
        $.each($('.checkeditems'), function($key, $item){
            if($($item).is(':checked')){
                $selectedItems[$count++] = $($item).val();
            }
        });
        
        if($count>0){
            $selectedItems = $selectedItems.join(',');
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            if($selectedItems != ''){
                location.href = "<?php echo $this->url(array('action' => 'delete-technician'), 'admin_users', true); ?>/id/"+$selectedItems+"/pg/"+$pageNumber;
            }
        }else{
            alert('<?php echo $this->translate('Sorry, you did not select any technician!'); ?>');
        }
    }
});
function deleteTechnician($itemId){
    if(confirm('<?php echo $this->translate('Are you sure to delete the technician?'); ?>')){
        if($itemId != ''){
            var $pageNumber = <?php echo $this->paginator->getCurrentPageNumber(); ?>;
            location.href = "<?php echo $this->url(array('action' => 'delete-technician'), 'admin_users', true); ?>/id/"+$itemId+"/pg/"+$pageNumber;
        }
    }
}
</script>