<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */
?>

<div>
    <div id="formholder">
        <h4>
            <i class="icon-user" style="vertical-align:middle; margin-top: -2px;"></i>
            <?php echo $this->translate('Account Activation'); ?>
        </h4>
        <h5>
            <?php 
                echo $this->translate('
                    The email address are you trying has been already taken by someone else,
                    if you are the owner of that company, please check your email Inbox!
                    We have sent an account activation link to your email. If you do not get the
                    email in your Inbox, please check the Spam or Junk folder.
                '); 
            ?>
        </h5>
        <div style="clear: both;"></div>
    </div>
</div>