<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */
?>

<div>
    <div id="formholder">
        <h4>
            <i class="icon-user" style="vertical-align:middle; margin-top: -2px;"></i>
            <?php echo $this->translate('Registration Successful!'); ?>
        </h4>
        <h5>
            <?php 
                echo $this->translate('
                    Congratulations! You have successfully registered with us. Though account
                    created successfully, still you can not use your account until you activate it.
                    We have sent a registration confirmation email with activation link, please
                    check your email Inbox! If you do not get the email in your Inbox, please check
                    the Spam or Junk folder.
                '); 
            ?>
        </h5>
        <div style="clear: both;"></div>
    </div>
</div>