<?php
/**
 * Heating Support System
 *
 * @category   Application_Core
 * @package    heating-system
 * @author     Suman Barua
 * @developer  Suman Barua <sumanbarua576@gmail.com>
 */

/**
 * @category   Application_Core
 * @package    heating-system
 */

//$notShow = array('core_main_profile');
$menu = array('menu' => 'core_main_settings_top');
echo $this->topMenuWidget(array('headtitle' => 'User Panel', 'menu' => $menu));
?>

<div>
    <div id="formholder">
        <h4>
            <i class="icon-home" style="vertical-align:middle; margin-top: -2px;"></i>
            <?php echo $this->translate('User Panel [Change Account Password]'); ?>
        </h4>
        <?php 
            if(!$this->success){
                echo $this->form->render($this);
            }else{
        ?>
        <h5><?php echo $this->translate('Password changed successfully, you will be automatically logged out now!'); ?></h5>
        <?php } ?>
        <div style="clear: both;"></div>
    </div>
</div>

<script type="text/javascript">
$('#submit').prepend("<i class='icon-ok-sign icon-white'></i> ");
<?php if($this->success): ?>
setTimeout(function(){
    location.href = "<?php echo $this->url(array(), 'member_logout', true); ?>";
}, 3000);
<?php endif; ?>    
</script>
